# Generated by Django 2.0.5 on 2018-05-27 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
        ('pols', '0002_auto_20180526_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='댓글')),
                ('image', models.ImageField(blank=True, null=True, upload_to='comment/%Y/%m/%d/', verbose_name='이미지')),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customuser.CustomUser')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploadfile/%Y/%m/%d/content', verbose_name='이미지 파일'),
        ),
        migrations.AddField(
            model_name='comment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pols.Question'),
        ),
    ]
